name: Elvis Linter

on: [push, pull_request]

jobs:

  run_lint:

    runs-on: ubuntu-latest

    container:
      image: erlang:22.1

    steps:
      - uses: actions/checkout@v1
      - name: Lint Changed Files
        run: sh git diff --name-only
